import type { Metadata } from "next";
import NewsExperience, { type Article, type GofEvent, type GalleryItem, type VideoItem } from "@/components/news/NewsExperience";

export const metadata: Metadata = {
  title: "News & Media | Gulf-O-Flex® Press Releases & Industry News",
  description:
    "Latest news, press releases, and industry updates from Gulf-O-Flex® - the GCC's leading rubber insulation manufacturer. Stay current with product launches, certifications, and market insights.",
  alternates: { canonical: "https://gulfoflex.com/news" },
};

const articles: Article[] = [
  {
    title: "Gulf-O-Flex® Opens the Region's First Thermal & Acoustic Insulation Experience Centre in Dubai",
    date: "July 2026",
    iso: "2026-07-15",
    category: "Events",
    color: "emerald",
    summary:
      "Gulf-O-Flex® has opened the region's first thermal and acoustic Insulation Experience Centre in Dubai, offering architects, consultants and contractors a hands-on space to explore its advanced insulation systems, as featured by Construction Week Online.",
    featured: true,
    readTime: 4,
    author: "GOF Newsroom",
    tags: ["Experience Centre", "Dubai", "Construction Week"],
    trending: true,
    image: "/images/news/experience-centre-dubai-construction-week.jpg",
    link: "https://www.constructionweekonline.com/news/gulf-o-flex-opens-the-regions-first-thermal-and-acoustic-insulation-experience-centre-in-dubai",
  },
  {
    title: "Gulf-O-Flex® Featured in MEP Middle East (ITP) for Sustainable Insulation Leadership",
    date: "July 2026",
    iso: "2026-07-02",
    category: "Media",
    color: "blue",
    summary:
      "Gulf-O-Flex® has been featured by MEP Middle East (ITP) highlighting our commitment to sustainable insulation manufacturing, zero-ODP product innovation, and regional infrastructure development.",
    featured: true,
    readTime: 3,
    author: "GOF Newsroom",
    tags: ["MEP", "Media", "Sustainability"],
    trending: true,
    image: "/images/news/mep-middle-east.jpg",
    link: "https://www.linkedin.com/posts/gulf-o-flex-rubber-world-industry-llc-has-share-7477963679293165569-qb91/?utm_source=share&utm_medium=member_desktop&rcm=ACoAAALMuecBU1PMGDGlh7bSJ9D6mXy40CrQPtM",
  },
  {
    title: "Gulf-O-Flex® Featured in Construction Week Middle East",
    date: "July 2026",
    iso: "2026-07-02",
    category: "Media",
    color: "emerald",
    summary:
      "Construction Week Middle East spotlights Gulf-O-Flex® as a leading insulation manufacturer driving energy efficiency and fire safety compliance across the GCC's most ambitious construction projects.",
    featured: true,
    readTime: 3,
    author: "GOF Newsroom",
    tags: ["Construction Week", "Media", "GCC"],
    trending: true,
    image: "/images/news/construction-week-middle-east.jpg",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7478083674450780160/",
  },
  {
    title: "Gulf-O-Flex® Featured by Startup Saudi for Construction Sustainability Innovation",
    date: "July 2026",
    iso: "2026-07-02",
    category: "Media",
    color: "purple",
    summary:
      "Startup Saudi highlights Gulf-O-Flex® as a sustainability-driven construction innovator, showcasing our advanced insulation solutions and their role in the Kingdom's green building transformation.",
    featured: true,
    readTime: 3,
    author: "KSA Team",
    tags: ["Startup Saudi", "KSA", "Sustainability"],
    trending: true,
    image: "/images/news/startup-saudi.jpg",
    link: "https://www.linkedin.com/posts/startup-saudi_dubai-construction-sustainability-activity-7478130417330638849-ut7n/?utm_source=share&utm_medium=member_ios&rcm=ACoAABc7zn0BdlC1Ou0tOxDIBCsjPPmHu6AWIDU",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at HVACR Nigeria 2026",
    date: "March 2026",
    iso: "2026-03-18",
    category: "Events",
    color: "orange",
    summary:
      "Gulf-O-Flex® returns to Lagos to showcase its full range of advanced thermal, acoustic, and fire-rated insulation solutions at HVACR Nigeria 2026 - Africa's premier HVAC, refrigeration and building services exhibition.",
    featured: true,
    readTime: 4,
    author: "Marketing",
    tags: ["HVACR", "Nigeria", "Trade Show"],
    trending: true,
    image: "/images/news/hvacr-nigeria-2026.jpeg",
    link: "https://www.linkedin.com/posts/rubberworldindustry_gulfoflex-rubberworldindustry-big5constructsaudi-activity-7296134791186247682-h760",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at Stadiums & Sports Innovation Summit KSA 2026",
    date: "March 2026",
    iso: "2026-03-04",
    category: "Events",
    color: "purple",
    summary:
      "Gulf-O-Flex® presented its acoustic and thermal insulation systems for world-class stadium and sports infrastructure projects at the Stadiums & Sports Innovation Summit in the Kingdom of Saudi Arabia.",
    featured: true,
    readTime: 4,
    author: "KSA Team",
    tags: ["KSA", "Stadiums", "Acoustic"],
    trending: true,
    image: "/images/news/stadiums-ksa-2026.jpeg",
  },
  {
    title: "Gulf-O-Flex® Recognized with Innovation Award at ASHRAE Cairo HVACR-R Expo 2026",
    date: "February 2026",
    iso: "2026-02-25",
    category: "Awards",
    color: "amber",
    summary:
      "Gulf-O-Flex® was honoured with an Innovation Recognition at the ASHRAE Cairo HVACR-R Expo 2026 for its low-GWP NBR formulation and the introduction of fully recyclable insulation packaging across the MENA region.",
    featured: true,
    readTime: 5,
    author: "GOF Newsroom",
    tags: ["ASHRAE", "Cairo", "Award", "Innovation"],
    trending: true,
    image: "/images/news/ashrae-cairo-2026.jpeg",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at AHR Expo Las Vegas, USA 2026",
    date: "February 2026",
    iso: "2026-02-02",
    category: "Events",
    color: "blue",
    summary:
      "Gulf-O-Flex® joined the world's largest HVACR show - AHR Expo 2026 in Las Vegas - to meet US specifiers, contractors and distributors and demonstrate its UL-listed and FM-approved insulation product range.",
    readTime: 4,
    author: "Commercial Desk",
    tags: ["AHR Expo", "USA", "Las Vegas"],
    trending: true,
    image: "/images/news/ahr-vegas-2026.jpg",
    link: "https://www.linkedin.com/posts/rubberworldindustry_gulfoflex-rubberworldindustry-big5constructsaudi-activity-7296134791186247682-h760",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at Pakistan HVACR Expo & Conference 2026",
    date: "January 2026",
    iso: "2026-01-22",
    category: "Events",
    color: "green",
    summary:
      "Gulf-O-Flex® strengthened its presence in South Asia at the Pakistan HVACR Expo & Conference 2026 in Karachi, where the team showcased NBR, XLPE and Aluglass solutions tailored for the region's growing infrastructure pipeline.",
    readTime: 3,
    author: "APAC Team",
    tags: ["Pakistan", "HVACR", "South Asia"],
    image: "/images/news/pakistan-hvacr-2026.jpg",
  },
  {
    title: "Gulf-O-Flex® Wins Innovation in Sustainable Engineering and Green Solution Award at One UAE Awards 2026",
    date: "January 2026",
    iso: "2026-01-15",
    category: "Awards",
    color: "emerald",
    summary:
      "Gulf-O-Flex® has been recognized with the Innovation in Sustainable Engineering and Green Solution Award at the One UAE Awards 2026 - celebrating our zero-ODP, low-GWP product range and our 40% reduction in embodied carbon.",
    featured: true,
    readTime: 5,
    author: "Sustainability",
    tags: ["UAE Awards", "Sustainability", "Green Solution"],
    trending: true,
    image: "/images/news/one-uae-awards-2026.jpg",
  },
  {
    title: "Leading Insulation: Gulf-O-Flex® at Big 5 Construct Saudi 2025",
    date: "November 2025",
    iso: "2025-11-18",
    category: "Events",
    color: "orange",
    summary:
      "Gulf-O-Flex® participated as a leading insulation brand at Big 5 Construct Saudi 2025 in Riyadh - meeting Saudi consultants, contractors and Vision 2030 mega-project teams to discuss locally manufactured Tier-1 insulation supply.",
    readTime: 4,
    author: "KSA Team",
    tags: ["Big 5", "KSA", "Riyadh"],
    trending: true,
    image: "/images/news/big5-construct-saudi-2025.jpg",
    link: "https://www.linkedin.com/posts/rubberworldindustry_gulfoflex-rubberworldindustry-big5constructsaudi-activity-7296134791186247682-h760",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at AHR Expo Orlando, USA 2025",
    date: "February 2025",
    iso: "2025-02-10",
    category: "Events",
    color: "blue",
    summary:
      "The Gulf-O-Flex® team exhibited at the AHR Expo Orlando 2025, presenting its UL-listed elastomeric insulation portfolio to North American mechanical contractors and HVAC engineers.",
    readTime: 3,
    author: "Commercial Desk",
    tags: ["AHR Expo", "USA", "Orlando"],
    image: "/images/news/ahr-orlando-2025.jpg",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at Big 5 Nigeria 2025",
    date: "October 2025",
    iso: "2025-10-14",
    category: "Events",
    color: "purple",
    summary:
      "Gulf-O-Flex® returned to Lagos for Big 5 Nigeria 2025 - engaging African MEP consultants, distributors and contractors with live demos of its rubber, glass-faced and aluminium-clad insulation systems.",
    readTime: 3,
    author: "Marketing",
    tags: ["Big 5", "Nigeria", "Africa"],
    image: "/images/news/big5-nigeria-2025.jpg",
  },
  {
    title: "Gulf-O-Flex® at MEPIC KSA Conference 2025",
    date: "September 2025",
    iso: "2025-09-09",
    category: "Events",
    color: "cyan",
    summary:
      "Gulf-O-Flex® joined leading Saudi MEP consultants and contractors at the MEPIC KSA Conference 2025 - sharing best-practice condensation control and fire-safety insulation specifications for Kingdom mega-projects.",
    readTime: 3,
    author: "KSA Team",
    tags: ["MEPIC", "KSA", "Conference"],
    image: "/images/news/mepic-ksa-2025.jpg",
    link: "https://www.linkedin.com/feed/update/urn:li:share:7115628986302369793/",
  },
  {
    title: "Rubber World Industry Proudly Showcased at ACREX India 2024",
    date: "February 2024",
    iso: "2024-02-29",
    category: "Events",
    color: "orange",
    summary:
      "Rubber World Industry - the makers of Gulf-O-Flex® - proudly exhibited at ACREX India 2024 in Mumbai, India's premier HVAC&R show, presenting our full insulation range to the Indian and South Asian engineering community.",
    readTime: 3,
    author: "APAC Team",
    tags: ["ACREX", "India", "Mumbai"],
    image: "/images/news/acrex-india-2024.jpg",
    link: "https://www.linkedin.com/feed/update/urn:li:share:7161966776719663104/",
  },
  {
    title: "Leading Insulation: Gulf-O-Flex® at Big 5 Global 2023",
    date: "December 2023",
    iso: "2023-12-04",
    category: "Events",
    color: "orange",
    summary:
      "Gulf-O-Flex® showcased its complete portfolio of NBR, XLPE, Aluglass, Aluclad and Sound insulation systems at Big 5 Global 2023 - the Middle East's largest construction event - at Dubai World Trade Centre.",
    readTime: 3,
    author: "Marketing",
    tags: ["Big 5", "Dubai", "Global"],
    image: "/images/news/big5-global-2023.jpg",
    link: "https://www.linkedin.com/feed/update/urn:li:ugcPost:7137494982529069056/",
  },
  {
    title: "Rubber World Industry Wins Major Awards in Two Categories at CBNME MEP Awards 2022",
    date: "October 2022",
    iso: "2022-10-20",
    category: "Awards",
    color: "amber",
    summary:
      "Rubber World Industry, the manufacturer behind Gulf-O-Flex®, was honoured with awards in two categories at the CBNME MEP Awards 2022 - recognising our innovation in insulation manufacturing and our contribution to the regional MEP industry.",
    featured: true,
    readTime: 4,
    author: "GOF Newsroom",
    tags: ["CBNME", "MEP Awards", "Award"],
    image: "/images/news/cbnme-mep-awards-2022.jpg",
    video: "https://www.youtube.com/watch?v=c5DBRwQfho4",
  },
  {
    title: "MEP Awards 2023 Sponsored by Gulf-O-Flex®",
    date: "October 2023",
    iso: "2023-10-12",
    category: "Awards",
    color: "amber",
    summary:
      "Gulf-O-Flex® was proud to sponsor the MEP Awards 2023 - supporting the Middle East's premier celebration of engineering excellence across mechanical, electrical and plumbing disciplines.",
    readTime: 3,
    author: "Marketing",
    tags: ["MEP Awards", "Sponsor", "Industry"],
    image: "/images/news/mep-awards-2023.jpg",
  },
  {
    title: "11th Annual Climate Control Awards",
    date: "September 2022",
    iso: "2022-09-15",
    category: "Awards",
    color: "blue",
    summary:
      "Gulf-O-Flex® was nominated at the 11th Annual Climate Control Awards - the region's most respected platform for honouring HVACR product excellence and engineering innovation.",
    readTime: 3,
    author: "Marketing",
    tags: ["Climate Control", "HVACR", "Awards"],
    image: "/images/news/climate-control-awards.jpg",
  },
  {
    title: "Gulf-O-Flex® Proudly Co-hosts The Client Consultant Contractor Conference",
    date: "May 2022",
    iso: "2022-05-19",
    category: "Events",
    color: "cyan",
    summary:
      "Gulf-O-Flex® co-hosted The Client–Consultant–Contractor Conference, bringing together project owners, design consultants and MEP contractors to discuss best practices in specification, value engineering and on-site execution.",
    readTime: 3,
    author: "Events Team",
    tags: ["Conference", "MEP", "Networking"],
    image: "/images/news/ccc-conference.jpeg",
    link: "https://gulfoflex.com/changing-the-world-through-green-thinking/",
  },
  {
    title: "MEP Conference 2021",
    date: "October 2021",
    iso: "2021-10-21",
    category: "Events",
    color: "purple",
    summary:
      "Gulf-O-Flex® joined regional MEP leaders at the MEP Conference 2021 - engaging in panel discussions on sustainable insulation, energy efficiency, and the post-pandemic outlook for the GCC construction industry.",
    readTime: 3,
    author: "Marketing",
    tags: ["MEP", "Conference", "GCC"],
    image: "/images/news/mep-conference-2021.jpeg",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:6830508705906266112/",
  },
  {
    title: "Changing The World Through Green Thinking",
    date: "June 2021",
    iso: "2021-06-08",
    category: "Sustainability",
    color: "emerald",
    summary:
      "Gulf-O-Flex® launched its Green Thinking initiative - committing to long-term carbon reduction, sustainable raw material sourcing, and full lifecycle accountability across our insulation manufacturing operations.",
    readTime: 5,
    author: "Sustainability",
    tags: ["Green", "Sustainability", "Initiative"],
    image: "/images/news/green-thinking.jpeg",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:6830508705906266112/",
  },
];

const categories = [
  "All",
  "Events",
  "Awards",
  "Sustainability",
  "Product Launch",
  "Certification",
  "Distribution",
  "Operations",
  "Projects",
  "Technical",
];

const events: GofEvent[] = [
  {
    title: "ISH Frankfurt 2025 - Recap",
    tagline: "Three days. 190+ qualified leads.",
    type: "Trade Show",
    color: "blue",
    startISO: "2025-03-17",
    endISO: "2025-03-21",
    dateLabel: "17 – 21 March 2025",
    location: "Messe Frankfurt, Germany",
    summary:
      "Our European debut at ISH Frankfurt set new benchmarks for engagement. Watch the highlight reel and download the post-show report.",
    image: "/images/news/ahr-vegas-2026.jpg",
    cta: { label: "Watch recap", href: "#" },
    status: "past",
  },
  {
    title: "Gulf-O-Flex® Factory Open Day",
    tagline: "30 years of manufacturing excellence",
    type: "Open House",
    color: "orange",
    startISO: "2025-12-08",
    endISO: "2025-12-08",
    dateLabel: "8 December 2025",
    location: "RAK Industrial Park, UAE",
    summary:
      "Customers, partners and media joined us for guided tours of the production line, R&D lab and quality control facilities.",
    image: "/images/news/green-thinking.jpeg",
    cta: { label: "View photos", href: "#" },
    status: "past",
  },
];

const gallery: GalleryItem[] = [
  { src: "/images/news/big5-construct-saudi-2025.jpg", caption: "Big 5 Construct Saudi 2025 - Riyadh", tag: "Event" },
  { src: "/images/news/ahr-vegas-2026.jpg", caption: "AHR Expo 2026 - Las Vegas, USA", tag: "Trade Show" },
  { src: "/images/news/one-uae-awards-2026.jpg", caption: "One UAE Awards 2026 - Green Solution", tag: "Award" },
  { src: "/images/news/acrex-india-2024.jpg", caption: "ACREX India 2024 - Mumbai", tag: "Event" },
  { src: "/images/news/hvacr-nigeria-2026.jpeg", caption: "HVACR Nigeria 2026 - Lagos", tag: "Trade Show" },
  { src: "/images/news/mep-awards-2023.jpg", caption: "MEP Awards 2023 - Sponsored", tag: "Award" },
  { src: "/images/news/pakistan-hvacr-2026.jpg", caption: "Pakistan HVACR Expo 2026 - Karachi", tag: "Event" },
  { src: "/images/news/big5-global-2023.jpg", caption: "Big 5 Global 2023 - Dubai", tag: "Trade Show" },
];

const videos: VideoItem[] = [
  { title: "Experience Centre Inauguration", url: "https://www.youtube.com/watch?v=_xBbdDqPclk" },
  { title: "Gulf-O-Flex® Corporate Overview", url: "https://www.youtube.com/watch?v=_O2ZHFaFFyM" },
  { title: "Product Range Showcase", url: "https://www.youtube.com/watch?v=qGekb0VosA4" },
  { title: "Manufacturing Excellence", url: "https://www.youtube.com/watch?v=juoWIase370" },
  { title: "Technical Applications", url: "https://www.youtube.com/watch?v=qAH6pfbrANY" },
  { title: "Quality & Testing", url: "https://www.youtube.com/watch?v=m4O2Cl7SpYM" },
  { title: "Global Presence", url: "https://www.youtube.com/watch?v=LhFXc1ToLbg" },
];

export default function NewsPage() {
  return <NewsExperience articles={articles} categories={categories} events={events} gallery={gallery} videos={videos} />;
}
