import type { Metadata } from "next";
import NewsExperience, { type Article, type GofEvent, type GalleryItem } from "@/components/news/NewsExperience";

export const metadata: Metadata = {
  title: "News & Media | Gulf-O-Flex® Press Releases & Industry News",
  description:
    "Latest news, press releases, and industry updates from Gulf-O-Flex® — the GCC's leading rubber insulation manufacturer. Stay current with product launches, certifications, and market insights.",
  alternates: { canonical: "https://gulfoflex.com/news" },
};

const articles: Article[] = [
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at HVACR Nigeria 2026",
    date: "March 2026",
    iso: "2026-03-18",
    category: "Events",
    color: "orange",
    summary:
      "Gulf-O-Flex® returns to Lagos to showcase its full range of advanced thermal, acoustic, and fire-rated insulation solutions at HVACR Nigeria 2026 — Africa's premier HVAC, refrigeration and building services exhibition.",
    featured: true,
    readTime: 4,
    author: "Marketing",
    tags: ["HVACR", "Nigeria", "Trade Show"],
    trending: true,
    image: "/images/products/nbr-banner.jpeg",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at Stadiums & Sports Innovation Summit KSA 2026",
    date: "March 2026",
    iso: "2026-03-04",
    category: "Events",
    color: "purple",
    summary:
      "Gulf-O-Flex® presented its acoustic and thermal insulation systems for world-class stadium and sports infrastructure projects at the Stadiums & Sports Innovation Summit in the Kingdom of Saudi Arabia.",
    featured: true,
    readTime: 4,
    author: "KSA Team",
    tags: ["KSA", "Stadiums", "Acoustic"],
    trending: true,
    image: "/images/products/sound-1.webp",
  },
  {
    title: "Gulf-O-Flex® Recognized with Innovation Award at ASHRAE Cairo HVACR-R Expo 2026",
    date: "February 2026",
    iso: "2026-02-25",
    category: "Awards",
    color: "amber",
    summary:
      "Gulf-O-Flex® was honoured with an Innovation Recognition at the ASHRAE Cairo HVACR-R Expo 2026 for its low-GWP NBR formulation and the introduction of fully recyclable insulation packaging across the MENA region.",
    featured: true,
    readTime: 5,
    author: "GOF Newsroom",
    tags: ["ASHRAE", "Cairo", "Award", "Innovation"],
    trending: true,
    image: "/images/products/aluclad-install.webp",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at AHR Expo Las Vegas, USA 2026",
    date: "February 2026",
    iso: "2026-02-02",
    category: "Events",
    color: "blue",
    summary:
      "Gulf-O-Flex® joined the world's largest HVACR show — AHR Expo 2026 in Las Vegas — to meet US specifiers, contractors and distributors and demonstrate its UL-listed and FM-approved insulation product range.",
    readTime: 4,
    author: "Commercial Desk",
    tags: ["AHR Expo", "USA", "Las Vegas"],
    trending: true,
    image: "/images/products/xlpe-banner.jpg",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at Pakistan HVACR Expo & Conference 2026",
    date: "January 2026",
    iso: "2026-01-22",
    category: "Events",
    color: "green",
    summary:
      "Gulf-O-Flex® strengthened its presence in South Asia at the Pakistan HVACR Expo & Conference 2026 in Karachi, where the team showcased NBR, XLPE and Aluglass solutions tailored for the region's growing infrastructure pipeline.",
    readTime: 3,
    author: "APAC Team",
    tags: ["Pakistan", "HVACR", "South Asia"],
    image: "/images/products/aluglass-install.webp",
  },
  {
    title: "Gulf-O-Flex® Wins Innovation in Sustainable Engineering and Green Solution Award at One UAE Awards 2026",
    date: "January 2026",
    iso: "2026-01-15",
    category: "Awards",
    color: "emerald",
    summary:
      "Gulf-O-Flex® has been recognized with the Innovation in Sustainable Engineering and Green Solution Award at the One UAE Awards 2026 — celebrating our zero-ODP, low-GWP product range and our 40% reduction in embodied carbon.",
    featured: true,
    readTime: 5,
    author: "Sustainability",
    tags: ["UAE Awards", "Sustainability", "Green Solution"],
    trending: true,
    image: "/images/products/nbr-roll.webp",
  },
  {
    title: "Leading Insulation: Gulf-O-Flex® at Big 5 Construct Saudi 2025",
    date: "November 2025",
    iso: "2025-11-18",
    category: "Events",
    color: "orange",
    summary:
      "Gulf-O-Flex® participated as a leading insulation brand at Big 5 Construct Saudi 2025 in Riyadh — meeting Saudi consultants, contractors and Vision 2030 mega-project teams to discuss locally manufactured Tier-1 insulation supply.",
    readTime: 4,
    author: "KSA Team",
    tags: ["Big 5", "KSA", "Riyadh"],
    trending: true,
    image: "/images/products/aluclad-2.webp",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at AHR Expo Orlando, USA 2025",
    date: "February 2025",
    iso: "2025-02-10",
    category: "Events",
    color: "blue",
    summary:
      "The Gulf-O-Flex® team exhibited at the AHR Expo Orlando 2025, presenting its UL-listed elastomeric insulation portfolio to North American mechanical contractors and HVAC engineers.",
    readTime: 3,
    author: "Commercial Desk",
    tags: ["AHR Expo", "USA", "Orlando"],
    image: "/images/products/nbr-pipe.jpeg",
  },
  {
    title: "Gulf-O-Flex® Showcases Advanced Insulation at Big 5 Nigeria 2025",
    date: "October 2025",
    iso: "2025-10-14",
    category: "Events",
    color: "purple",
    summary:
      "Gulf-O-Flex® returned to Lagos for Big 5 Nigeria 2025 — engaging African MEP consultants, distributors and contractors with live demos of its rubber, glass-faced and aluminium-clad insulation systems.",
    readTime: 3,
    author: "Marketing",
    tags: ["Big 5", "Nigeria", "Africa"],
    image: "/images/products/aluglass-tube.webp",
  },
  {
    title: "Gulf-O-Flex® at MEPIC KSA Conference 2025",
    date: "September 2025",
    iso: "2025-09-09",
    category: "Events",
    color: "cyan",
    summary:
      "Gulf-O-Flex® joined leading Saudi MEP consultants and contractors at the MEPIC KSA Conference 2025 — sharing best-practice condensation control and fire-safety insulation specifications for Kingdom mega-projects.",
    readTime: 3,
    author: "KSA Team",
    tags: ["MEPIC", "KSA", "Conference"],
    image: "/images/products/nbr-banner.jpeg",
  },
  {
    title: "Rubber World Industry Proudly Showcased at ACREX India 2024",
    date: "February 2024",
    iso: "2024-02-29",
    category: "Events",
    color: "orange",
    summary:
      "Rubber World Industry — the makers of Gulf-O-Flex® — proudly exhibited at ACREX India 2024 in Mumbai, India's premier HVAC&R show, presenting our full insulation range to the Indian and South Asian engineering community.",
    readTime: 3,
    author: "APAC Team",
    tags: ["ACREX", "India", "Mumbai"],
    image: "/images/products/aluclad-install.webp",
  },
  {
    title: "Leading Insulation: Gulf-O-Flex® at Big 5 Global 2023",
    date: "December 2023",
    iso: "2023-12-04",
    category: "Events",
    color: "orange",
    summary:
      "Gulf-O-Flex® showcased its complete portfolio of NBR, XLPE, Aluglass, Aluclad and Sound insulation systems at Big 5 Global 2023 — the Middle East's largest construction event — at Dubai World Trade Centre.",
    readTime: 3,
    author: "Marketing",
    tags: ["Big 5", "Dubai", "Global"],
    image: "/images/products/aluclad-1.webp",
  },
  {
    title: "Rubber World Industry Wins Major Awards in Two Categories at CBNME MEP Awards 2022",
    date: "October 2022",
    iso: "2022-10-20",
    category: "Awards",
    color: "amber",
    summary:
      "Rubber World Industry, the manufacturer behind Gulf-O-Flex®, was honoured with awards in two categories at the CBNME MEP Awards 2022 — recognising our innovation in insulation manufacturing and our contribution to the regional MEP industry.",
    featured: true,
    readTime: 4,
    author: "GOF Newsroom",
    tags: ["CBNME", "MEP Awards", "Award"],
    image: "/images/products/sound-2.webp",
  },
  {
    title: "MEP Awards 2023 Sponsored by Gulf-O-Flex®",
    date: "October 2023",
    iso: "2023-10-12",
    category: "Awards",
    color: "amber",
    summary:
      "Gulf-O-Flex® was proud to sponsor the MEP Awards 2023 — supporting the Middle East's premier celebration of engineering excellence across mechanical, electrical and plumbing disciplines.",
    readTime: 3,
    author: "Marketing",
    tags: ["MEP Awards", "Sponsor", "Industry"],
    image: "/images/products/aluglass-sheet.webp",
  },
  {
    title: "11th Annual Climate Control Awards",
    date: "September 2022",
    iso: "2022-09-15",
    category: "Awards",
    color: "blue",
    summary:
      "Gulf-O-Flex® was nominated at the 11th Annual Climate Control Awards — the region's most respected platform for honouring HVACR product excellence and engineering innovation.",
    readTime: 3,
    author: "Marketing",
    tags: ["Climate Control", "HVACR", "Awards"],
    image: "/images/products/xlpe-banner.jpg",
  },
  {
    title: "Gulf-O-Flex® Proudly Co-hosts The Client Consultant Contractor Conference",
    date: "May 2022",
    iso: "2022-05-19",
    category: "Events",
    color: "cyan",
    summary:
      "Gulf-O-Flex® co-hosted The Client–Consultant–Contractor Conference, bringing together project owners, design consultants and MEP contractors to discuss best practices in specification, value engineering and on-site execution.",
    readTime: 3,
    author: "Events Team",
    tags: ["Conference", "MEP", "Networking"],
    image: "/images/products/aluglass-install.webp",
  },
  {
    title: "MEP Conference 2021",
    date: "October 2021",
    iso: "2021-10-21",
    category: "Events",
    color: "purple",
    summary:
      "Gulf-O-Flex® joined regional MEP leaders at the MEP Conference 2021 — engaging in panel discussions on sustainable insulation, energy efficiency, and the post-pandemic outlook for the GCC construction industry.",
    readTime: 3,
    author: "Marketing",
    tags: ["MEP", "Conference", "GCC"],
    image: "/images/products/nbr-roll.webp",
  },
  {
    title: "Changing The World Through Green Thinking",
    date: "June 2021",
    iso: "2021-06-08",
    category: "Sustainability",
    color: "emerald",
    summary:
      "Gulf-O-Flex® launched its Green Thinking initiative — committing to long-term carbon reduction, sustainable raw material sourcing, and full lifecycle accountability across our insulation manufacturing operations.",
    readTime: 5,
    author: "Sustainability",
    tags: ["Green", "Sustainability", "Initiative"],
    image: "/images/products/aluclad-install.webp",
  },
];

const categories = [
  "All",
  "Events",
  "Awards",
  "Sustainability",
  "Product Launch",
  "Certification",
  "Distribution",
  "Operations",
  "Projects",
  "Technical",
];

const events: GofEvent[] = [
  {
    title: "Big 5 Global 2026",
    tagline: "Premium Sponsor · Stand C3-220",
    type: "Trade Show",
    color: "orange",
    startISO: "2026-11-23",
    endISO: "2026-11-26",
    dateLabel: "23 – 26 November 2026",
    location: "Dubai World Trade Centre, UAE",
    summary:
      "Experience the full Gulf-O-Flex® range at the largest construction event in the Middle East. Live demos, technical clinics, and exclusive previews of our 2027 product roadmap.",
    image: "/images/products/aluclad-install.webp",
    cta: { label: "Book a meeting", href: "/contact" },
    featured: true,
    status: "upcoming",
  },
  {
    title: "Saudi Build Riyadh 2026",
    tagline: "Vision 2030 Construction Summit",
    type: "Exhibition",
    color: "cyan",
    startISO: "2026-10-12",
    endISO: "2026-10-15",
    dateLabel: "12 – 15 October 2026",
    location: "Riyadh Front Expo Centre, KSA",
    summary:
      "Meet the Gulf-O-Flex® KSA team and discover how our locally manufactured rubber insulation is fuelling the Kingdom's mega-projects under Vision 2030.",
    image: "/images/products/nbr-banner.jpeg",
    cta: { label: "Add to calendar", href: "#" },
    status: "upcoming",
  },
  {
    title: "Acoustic Insulation Webinar",
    tagline: "Live technical session with our R&D team",
    type: "Webinar",
    color: "purple",
    startISO: "2026-07-09",
    endISO: "2026-07-09",
    dateLabel: "9 July 2026 · 14:00 GST",
    location: "Online · Microsoft Teams",
    summary:
      "Deep-dive into Gulf-O-Flex® Sound — STC ratings, installation best practices, and case studies from Riyadh Metro Phase 2.",
    image: "/images/products/sound-1.webp",
    cta: { label: "Register free", href: "#" },
    status: "upcoming",
  },
  {
    title: "MEP Expo Mumbai 2026",
    tagline: "Distributor & specifier meet",
    type: "Exhibition",
    color: "green",
    startISO: "2026-09-03",
    endISO: "2026-09-05",
    dateLabel: "3 – 5 September 2026",
    location: "Bombay Exhibition Centre, India",
    summary:
      "Gulf-O-Flex® returns to MEP Expo with our APAC distribution partners — featuring the new low-GWP NBR range and Aluclad jacketing systems.",
    image: "/images/products/aluclad-2.webp",
    cta: { label: "View details", href: "#" },
    status: "upcoming",
  },
  {
    title: "ISH Frankfurt 2025 — Recap",
    tagline: "Three days. 190+ qualified leads.",
    type: "Trade Show",
    color: "blue",
    startISO: "2025-03-17",
    endISO: "2025-03-21",
    dateLabel: "17 – 21 March 2025",
    location: "Messe Frankfurt, Germany",
    summary:
      "Our European debut at ISH Frankfurt set new benchmarks for engagement. Watch the highlight reel and download the post-show report.",
    image: "/images/products/xlpe-banner.jpg",
    cta: { label: "Watch recap", href: "#" },
    status: "past",
  },
  {
    title: "Gulf-O-Flex® Factory Open Day",
    tagline: "30 years of manufacturing excellence",
    type: "Open House",
    color: "orange",
    startISO: "2025-12-08",
    endISO: "2025-12-08",
    dateLabel: "8 December 2025",
    location: "RAK Industrial Park, UAE",
    summary:
      "Customers, partners and media joined us for guided tours of the production line, R&D lab and quality control facilities.",
    image: "/images/products/nbr-roll.webp",
    cta: { label: "View photos", href: "#" },
    status: "past",
  },
];

const gallery: GalleryItem[] = [
  { src: "/images/products/aluclad-install.webp", caption: "Aluclad jacketing — on-site, Dubai", tag: "Project" },
  { src: "/images/products/sound-2.webp", caption: "Sound insulation — Metro Phase 2", tag: "Acoustics" },
  { src: "/images/products/nbr-banner.jpeg", caption: "NBR production — KSA facility", tag: "Manufacturing" },
  { src: "/images/products/xlpe-banner.jpg", caption: "XLPE — FM Approved range", tag: "Certification" },
  { src: "/images/products/aluglass-install.webp", caption: "Aluglass install — Riyadh tower", tag: "Project" },
  { src: "/images/products/aluclad-2.webp", caption: "Aluclad — long-run delivery", tag: "Logistics" },
  { src: "/images/products/sound-1.webp", caption: "Acoustic test chamber", tag: "R&D" },
  { src: "/images/products/nbr-pipe.jpeg", caption: "Pipe section — pre-cut to spec", tag: "Product" },
];

export default function NewsPage() {
  return <NewsExperience articles={articles} categories={categories} events={events} gallery={gallery} />;
}
